name: AM64DS
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        include:
          - name: AM64DS
            args:
          - name: AM64DS Debug
            args: DEBUG_LOG=1
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    container: ghcr.io/lrflew/devkitppc:20211103
    steps:
      - name: Checkout AM64DS
        uses: actions/checkout@v2
      - name: Build
        run: make ${{ matrix.args }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: am64ds.rpx
