name: AM64DS
on: [push, pull_request]
jobs:
  build-stable:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:20210726
    steps:
      - name: Checkout AM64DS
        uses: actions/checkout@v2
      - name: Build
        run: make
  build-latest:
    continue-on-error: true
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
      - name: Update devkitPRO
        run: dkp-pacman -Syyu --noconfirm
      - name: Checkout AM64DS
        uses: actions/checkout@v2
      - name: Build
        run: make
      - name: Package
        run: make package
